# Site Details
name: Careers | Cascade Agronomics
description: The careers page for Cascade Agronomics.

# Config
markdown: redcarpet
permalink: pretty
pygments: true
timezone: America/Seattle
url: "http://cascadeagronomics.us/careers"

# Excludes
exclude: ['vendor']
